import test from 'node:test';
import assert from 'node:assert/strict';
import { PaintCore, LIMITS } from '../src/core.js';
import { executeJob } from '../src/agent.js';
import fs from 'node:fs';
const make = () => new PaintCore({ documentId: 'test', width: 8, height: 8 });
const run = (c, commands, id = `b-${c.getState().revision}`) => c.applyBatch({ documentId: 'test', batchId: id, expectedRevision: c.getState().revision, commands });
const add = { type: 'layer.add', id: 'ink', name: 'Ink' };
const dot = (x = 2, y = 3, color = '#FF0000FF') => ({ type: 'pixel.set', layerId: 'ink', x, y, color });
const pixel = (c, x, y) => Array.from(c.composite().data.slice((y * 8 + x) * 4, (y * 8 + x) * 4 + 4));
const fails = (fn, code) => assert.throws(fn, e => e.code === code);
test('blank is transparent, no implicit layers', () => { const c = make(); assert.equal(c.getState().revision, 0); assert.ok(c.composite().data.every(v => v === 0)); });
test('add and pixel set commit once', () => { const c = make(); run(c, [add, dot()]); assert.equal(c.getState().revision, 1); assert.deepEqual(pixel(c, 2, 3), [255, 0, 0, 255]); });
test('unknown commands do not mutate state', () => { const c = make(); fails(() => run(c, [add, { type: 'eval', source: 'x' }]), 'UNKNOWN_COMMAND'); assert.equal(c.getState().layers.length, 0); });
test('failure after a valid operation rolls back everything', () => { const c = make(); fails(() => run(c, [add, dot(99)]), 'OUT_OF_BOUNDS'); assert.equal(c.getState().revision, 0); assert.equal(c.getState().layers.length, 0); });
test('unknown fields and non-integer coordinates rejected', () => { const c = make(); run(c, [add]); fails(() => run(c, [{ ...dot(), evil: 1 }]), 'INVALID_INPUT'); fails(() => run(c, [dot(.5)]), 'INVALID_INPUT'); });
test('stale revision and document guards', () => { const c = make(); run(c, [add]); fails(() => c.applyBatch({ documentId: 'test', batchId: 'new', expectedRevision: 0, commands: [dot()] }), 'REVISION_CONFLICT'); fails(() => c.applyBatch({ documentId: 'other', batchId: 'new', expectedRevision: 1, commands: [dot()] }), 'DOCUMENT_CONFLICT'); });
test('same batch replay is idempotent even after undo', () => {
  const c = make(), b = { documentId: 'test', batchId: 'same', expectedRevision: 0, commands: [add, dot()] };
  c.applyBatch(b); assert.equal(c.applyBatch(b).replayed, true); assert.equal(c.getState().revision, 1);
  c.undo({ documentId: 'test', expectedRevision: 1 }); assert.equal(c.applyBatch(b).appliedRevision, 1); assert.equal(c.getState().layers.length, 0);
  fails(() => c.applyBatch({ ...b, commands: [add] }), 'IDEMPOTENCY_CONFLICT');
});
test('canonical replay ignores object property ordering', () => { const c = make(); run(c, [add], 'id'); assert.equal(c.applyBatch({ commands: [{ name: 'Ink', id: 'ink', type: 'layer.add' }], expectedRevision: 0, batchId: 'id', documentId: 'test' }).replayed, true); });
test('undo and redo revision numbers are monotonically increasing', () => { const c = make(); run(c, [add, dot()]); c.undo({ documentId: 'test', expectedRevision: 1 }); assert.equal(c.getState().revision, 2); c.redo({ documentId: 'test', expectedRevision: 2 }); assert.equal(c.getState().revision, 3); assert.deepEqual(pixel(c, 2, 3), [255, 0, 0, 255]); });
test('new edit clears redo history', () => { const c = make(); run(c, [add]); run(c, [dot()]); c.undo({ documentId: 'test', expectedRevision: 2 }); run(c, [dot(1)]); assert.equal(c.getState().canRedo, false); });
test('layer lock prevents edits, explicit unlock works', () => { const c = make(); run(c, [add, { type: 'layer.setProperties', layerId: 'ink', properties: { locked: true } }]); fails(() => run(c, [dot()]), 'LAYER_LOCKED'); run(c, [{ type: 'layer.setProperties', layerId: 'ink', properties: { locked: false } }, dot()]); });
test('layer visibility, ordering and opacity use source-over', () => {
  const c = make(); run(c, [add, dot(), { type: 'layer.add', id: 'top', name: 'Top' }, { ...dot(2, 3, '#0000FFFF'), layerId: 'top' }, { type: 'layer.setProperties', layerId: 'top', properties: { opacity: .5 } }]);
  assert.deepEqual(pixel(c, 2, 3), [128, 0, 128, 255]); run(c, [{ type: 'layer.reorder', layerId: 'ink', index: 1 }]); assert.deepEqual(pixel(c, 2, 3), [255, 0, 0, 255]);
  run(c, [{ type: 'layer.setProperties', layerId: 'ink', properties: { visible: false } }]); assert.deepEqual(pixel(c, 2, 3), [0, 0, 255, 128]);
});
test('line uses inclusive endpoints', () => { const c = make(); run(c, [add, { type: 'shape.line', layerId: 'ink', x: 0, y: 0, x2: 7, y2: 7, color: '#123456FF' }]); for (let i = 0; i < 8; i++) assert.equal(pixel(c, i, i)[3], 255); });
test('stroke overlap does not accumulate alpha', () => { const c = make(); run(c, [add, { type: 'brush.stroke', layerId: 'ink', points: [{ x: 2, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }], size: 3, color: '#FFFFFF80' }]); assert.equal(pixel(c, 2, 2)[3], 128); });
test('eraser clears RGBA, not opaque white', () => { const c = make(); run(c, [add, dot(), { type: 'eraser.stroke', layerId: 'ink', points: [{ x: 2, y: 3 }], size: 1 }]); assert.deepEqual(pixel(c, 2, 3), [0, 0, 0, 0]); });
test('rect uses half-open bounds and clips outside canvas', () => { const c = make(); run(c, [add, { type: 'shape.rect', layerId: 'ink', x: -1, y: 0, width: 3, height: 2, fill: '#FF0000FF' }]); assert.equal(pixel(c, 1, 1)[3], 255); assert.equal(pixel(c, 2, 1)[3], 0); });
test('ellipse is symmetric and pixel-only', () => { const c = make(); run(c, [add, { type: 'shape.ellipse', layerId: 'ink', x: 0, y: 0, width: 8, height: 8, fill: '#FF0000FF' }]); for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) { assert.deepEqual(pixel(c, x, y), pixel(c, 7 - x, 7 - y)); assert.ok([0, 255].includes(pixel(c, x, y)[3])); } });
test('fill is four-connected and respects boundaries', () => { const c = make(); run(c, [add, { type: 'shape.line', layerId: 'ink', x: 4, y: 0, x2: 4, y2: 7, color: '#FFFFFFFF' }, { type: 'fill.bucket', layerId: 'ink', x: 0, y: 0, color: '#FF0000FF' }]); assert.equal(pixel(c, 3, 7)[3], 255); assert.equal(pixel(c, 5, 0)[3], 0); });
test('fill with the same color terminates', () => { const c = make(); run(c, [add, { type: 'fill.bucket', layerId: 'ink', x: 0, y: 0, color: '#00000000' }]); assert.ok(c.composite().data.every(v => v === 0)); });
test('replace compares all RGBA channels within tolerance', () => { const c = make(); run(c, [add, dot(), { type: 'color.replace', layerId: 'ink', from: '#FE0000FF', to: '#00FF00FF', tolerance: 1 }]); assert.deepEqual(pixel(c, 2, 3), [0, 255, 0, 255]); });
test('project snapshot roundtrip preserves each layer and pixels', () => { const c = make(); run(c, [add, dot()]); const p = JSON.parse(JSON.stringify(c.exportProject())), d = PaintCore.fromProject(p, 'new-doc'); assert.deepEqual(d.composite(), c.composite()); assert.equal(d.getState().revision, 0); assert.equal(d.getState().documentId, 'new-doc'); });
test('malformed project, duplicate layers, invalid Base64 rejected', () => { const c = make(); run(c, [add]); const p = c.exportProject(); fails(() => PaintCore.fromProject({ ...p, encoding: 'url' }), 'INVALID_PROJECT'); fails(() => PaintCore.fromProject({ ...p, layers: [p.layers[0], p.layers[0]] }), 'INVALID_PROJECT'); fails(() => PaintCore.fromProject({ ...p, layers: [{ ...p.layers[0], pixels: 'AAAA' }] }), 'INVALID_PROJECT'); });
test('external snapshots cannot mutate the engine', () => { const c = make(); run(c, [add]); const s = c.getState(); s.layers[0].locked = true; run(c, [dot()]); const r = c.composite(); r.data.fill(0); assert.equal(pixel(c, 2, 3)[3], 255); });
test('invalid mode, size, color and layer count are guarded', () => { fails(() => new PaintCore({ mode: 'paint' }), 'UNSUPPORTED_MODE'); fails(() => new PaintCore({ width: 99999 }), 'INVALID_INPUT'); const c = make(); fails(() => run(c, [add, dot(0, 0, 'red')]), 'INVALID_COLOR'); fails(() => run(c, Array.from({ length: LIMITS.layers + 1 }, (_, i) => ({ ...add, id: `l${i}` }))), 'RESOURCE_LIMIT'); });
test('work budget is checked before expensive operations', () => { const c = make(); fails(() => run(c, [add, { type: 'brush.stroke', layerId: 'ink', size: 64, color: '#FFFFFFFF', points: [{ x: -4096, y: -4096 }, { x: 4096, y: 4096 }] }]), 'RESOURCE_LIMIT'); });
test('history is bounded', () => { const c = make(); run(c, [add]); for (let i = 0; i < 60; i++) run(c, [dot()]); let n = 0; while (c.getState().canUndo) { c.undo({ documentId: 'test', expectedRevision: c.getState().revision }); n++; } assert.equal(n, LIMITS.historyEntries); });
test('job replay is deterministic and checks dimensions / colors', () => { const j = JSON.parse(fs.readFileSync(new URL('../examples/slime.json', import.meta.url))); const a = executeJob(j), b = executeJob(j); assert.deepEqual(a.core.composite(), b.core.composite()); assert.equal(a.checks.passed, true); fails(() => executeJob({ ...j, checks: { ...j.checks, maxOpaqueColors: 1 } }), 'CHECK_FAILED'); fails(() => executeJob({ ...j, rendererProfile: 'latest-remote-code' }), 'UNSUPPORTED_PROFILE'); });
